const baseInventory = [
  { "title": "Acetaminophen 500mg Tablets", "description": "Pain reliever and fever reducer for headaches, muscle aches, and minor arthritis pain.", "price": 8.99 },
  { "title": "Ibuprofen 200mg Tablets", "description": "Nonsteroidal anti-inflammatory drug (NSAID) for relief of pain, inflammation, and fever.", "price": 9.49 },
  { "title": "Aspirin 81mg Low Dose", "description": "Low-dose aspirin commonly used for heart health and mild pain relief.", "price": 7.99 },
  { "title": "Cold & Flu Relief Capsules", "description": "Multi-symptom cold and flu relief for congestion, cough, and body aches.", "price": 12.99 },
  { "title": "Allergy Relief Antihistamine", "description": "24-hour allergy relief from sneezing, runny nose, and itchy eyes.", "price": 14.49 },
  { "title": "Cough Suppressant Syrup", "description": "Soothing cough syrup for temporary relief from dry coughs.", "price": 10.99 },
  { "title": "Throat Lozenges Honey Lemon", "description": "Soothing lozenges to relieve sore throat and throat irritation.", "price": 4.99 },
  { "title": "Antacid Chewable Tablets", "description": "Fast-acting relief from heartburn, acid indigestion, and upset stomach.", "price": 6.99 },
  { "title": "Probiotic Digestive Capsules", "description": "Daily probiotic to support digestive health and gut balance.", "price": 18.99 },
  { "title": "Laxative Stool Softener", "description": "Gentle stool softener for occasional constipation relief.", "price": 9.99 },
  { "title": "Anti-Diarrheal Tablets", "description": "Controls symptoms of diarrhea and helps restore digestive comfort.", "price": 7.49 },
  { "title": "Motion Sickness Relief Tablets", "description": "Prevents nausea, dizziness, and vomiting due to motion sickness.", "price": 8.49 },
  { "title": "Sleep Aid Melatonin 5mg", "description": "Melatonin supplement to support restful sleep and healthy sleep cycles.", "price": 11.99 },
  { "title": "Sleep Aid Nighttime Capsules", "description": "Non-habit forming sleep aid for occasional sleeplessness.", "price": 13.49 },
  { "title": "Hydrocortisone Anti-Itch Cream", "description": "Relieves itching and irritation from insect bites, rashes, and eczema.", "price": 6.49 },
  { "title": "Antibiotic Ointment", "description": "Helps prevent infection in minor cuts, scrapes, and burns.", "price": 5.99 },
  { "title": "Adhesive Bandages Assorted", "description": "Assorted sizes of adhesive bandages for minor wounds.", "price": 4.49 },
  { "title": "Digital Thermometer", "description": "Fast and accurate digital thermometer for oral temperature readings.", "price": 12.49 },
  { "title": "Hand Sanitizer Gel", "description": "Kills 99.9% of germs without water using alcohol-based formula.", "price": 3.99 },
  { "title": "Antiseptic Wipes", "description": "Disposable wipes for cleaning skin and preventing infection.", "price": 5.49 },
  { "title": "First Aid Gauze Pads", "description": "Sterile gauze pads for wound dressing and minor injuries.", "price": 6.99 },
  { "title": "Elastic Compression Bandage", "description": "Provides support and compression for sprains and strains.", "price": 8.99 },
  { "title": "Vitamin C 1000mg Tablets", "description": "Immune support supplement with high-potency vitamin C.", "price": 14.99 },
  { "title": "Multivitamin Gummies", "description": "Daily multivitamin gummies to support overall health.", "price": 15.49 },
  { "title": "Vitamin D3 Softgels", "description": "Supports bone health and immune function.", "price": 13.99 },
  { "title": "Calcium Magnesium Supplement", "description": "Supports bone strength and muscle function.", "price": 16.99 },
  { "title": "Omega-3 Fish Oil Capsules", "description": "Supports heart, brain, and joint health.", "price": 19.99 },
  { "title": "Blood Pressure Monitor", "description": "Automatic arm blood pressure monitor for home use.", "price": 49.99 },
  { "title": "Glucose Test Strips", "description": "Test strips for monitoring blood glucose levels.", "price": 24.99 },
  { "title": "Foot Pain Relief Cream", "description": "Cooling cream to relieve sore, tired feet.", "price": 7.99 },
  { "title": "Muscle Pain Relief Gel", "description": "Topical gel for fast relief of muscle and joint pain.", "price": 9.99 },
  { "title": "Heating Pad", "description": "Electric heating pad for muscle relaxation and pain relief.", "price": 29.99 },
  { "title": "Cold Pack Reusable", "description": "Reusable cold pack for swelling and injury treatment.", "price": 8.99 },
  { "title": "Nasal Saline Spray", "description": "Gentle saline spray to relieve nasal dryness and congestion.", "price": 6.49 },
  { "title": "Neti Pot Sinus Rinse", "description": "Sinus rinse system to flush allergens and congestion.", "price": 14.99 },
  { "title": "Eye Drops Lubricating", "description": "Relieves dry, irritated eyes with long-lasting moisture.", "price": 7.99 },
  { "title": "Contact Lens Solution", "description": "Cleans, disinfects, and stores contact lenses.", "price": 10.99 },
  { "title": "Feminine Hygiene Wash", "description": "pH-balanced wash for daily feminine hygiene.", "price": 8.49 },
  { "title": "Pregnancy Test Kit", "description": "At-home pregnancy test with fast and accurate results.", "price": 12.99 },
  { "title": "Oral Rehydration Electrolyte Powder", "description": "Electrolyte powder to prevent dehydration.", "price": 9.49 },
  { "title": "Protein Nutrition Shake", "description": "Ready-to-drink protein shake for nutritional support.", "price": 3.49 },
  { "title": "Fiber Supplement Powder", "description": "Supports digestive health and regularity.", "price": 14.49 },
  { "title": "Nicotine Gum", "description": "Helps reduce cravings and withdrawal symptoms.", "price": 29.99 },
  { "title": "Smoking Cessation Lozenges", "description": "Nicotine lozenges to help quit smoking.", "price": 34.99 },
  { "title": "Hemorrhoid Relief Cream", "description": "Provides relief from discomfort, itching, and swelling.", "price": 11.49 },
  { "title": "Insect Bite Relief Stick", "description": "Instant relief from itching and irritation caused by insect bites.", "price": 4.99 },
  { "title": "Alcohol Prep Pads", "description": "Sterile alcohol pads for disinfecting skin before injections or wound care.", "price": 3.99 },
  { "title": "Pain Relief Patches", "description": "Topical pain relief patches for muscle aches and joint discomfort.", "price": 12.49 },
  { "title": "Facial Tissues", "description": "Kleenex brand facial wipes 300ct", "price": 4.15},
  { "title": "Eyedrops", "description": "Over-the-counter eye drops for dry eye relief", "price": 2.28}
]

export default baseInventory